name: PushGitlab

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Push To Gitlab
              env:
                  token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
              run: |
                  echo Starting to push repo to gitlab
                  git config user.name "Lost4295"
                  git config user.email "yturinkondi@myges.fr"
                  git remote set-url origin "https://oauth2:${token}@gitlab.bonnard.io/KaiYou/discord-bot.git"
                  git push origin master
